// Publication content as flat data.
// type:   "toc"      — table-of-contents line (tight)
//         "p"        — body paragraph
//         "spacer"   — vertical gap between sections
//         "image"    — figure with image + caption (drawn onto the flag)
// indent: true       — first-line indent on the paragraph
// link:   "anchor"   — turns a toc entry into a hyperlink to that anchor
// anchor: "anchor"   — marks the first paragraph of a section as a jump target
// src / caption / credit — used by "image" blocks

export const blocks = [
  // Cover (was the hero — now lives on the flag itself, scrolling beneath the video)
  { type: "toc", text: "Research Publication" },
  { type: "toc", text: "Designing a Visual Identity Through Motion, Material, and Simulation" },
  { type: "spacer" },
  { type: "toc", text: "1048261" },
  { type: "toc", text: "Albert Kozikowski" },
  { type: "toc", text: "Graphic Design / Commercial" },
  { type: "toc", text: "Supervisors: Gabrielle Marks, Deanna Herst" },
  { type: "spacer" },
  { type: "toc", text: "WdKA Rotterdam 2026" },
  { type: "spacer" },
  { type: "spacer" },

  // Table of contents
  { type: "toc", text: "Introduction",                           link: "introduction" },
  { type: "toc", text: "Research Question",                      link: "research-question" },
  { type: "toc", text: "Research Approach",                      link: "research-approach" },
  { type: "toc", text: "1 — What Flags Claim",                   link: "section-1" },
  { type: "toc", text: "2 — The Flag as Medium",                 link: "section-2" },
  { type: "toc", text: "3 — Designing Through Simulation",       link: "section-3" },
  { type: "toc", text: "4 — What I Found and What I Don't Know", link: "section-4" },
  { type: "toc", text: "Flag Studio (opens in new tab)",         href: "https://thisoneiseasytospell.github.io/KOZI-Playground/Flag/index.html" },
  { type: "toc", text: "Conclusion",                             link: "conclusion" },
  { type: "toc", text: "Recommendations for Further Research",   link: "recommendations" },
  { type: "toc", text: "Statement of Originality",               link: "originality" },
  { type: "toc", text: "Source List",                            link: "sources" },
  { type: "spacer" },

  // Introduction
  { type: "p", indent: true, anchor: "introduction", text: "For the Willem de Kooning Academy Graduation Show 2026, Albert was selected to design the visual identity — the graphic face of the event across print, screen, and physical space. The identity takes the form of a flag." },
  { type: "p", text: "Albert Kozikowski (1997, Poland) is a designer working between generative, motion, and 3D design, and increasingly between the screen and the physical object. He works fast, switching tools when an idea flattens. That restlessness is part of the method. He oscillates between Norway and the Netherlands, and has worked with studios and brands including Studio Dumbar, LVMH, Snøhetta, and Canada Goose." },
  { type: "p", text: "This background matters for how the project was approached. A designer trained primarily in still graphic design might have produced a flag as a fixed mark and then animated it for digital use. Albert started from the opposite instinct. Motion was assumed from the beginning, and the static version was treated as the harder, less certain artifact." },
  { type: "p", text: "The flag was chosen as the identity for what it claims. In its oldest sense a flag is a marker raised to signal that something has been achieved, that someone is here. It is also a signal of departure. A graduation holds both at once: the arrival at the end of years of work, and the start of moving on. The 2026 cohort began studying just after COVID restrictions lifted, in years where the sense of a shared reality kept fragmenting through new forms of intelligence, ongoing wars, and new conflicts. A flag is a deliberately modest response to that. It is a single shared marker for a collective moment, carrying completion and pride without overstatement." },
  { type: "p", text: "But designing the flag raised a problem that was not anticipated. A flag is not a still image. It moves, drapes, catches wind, and is seen from both sides and many distances. The version of the design that worked on screen was not the version that worked on fabric. The moving version of the identity was stronger than any single frame extracted from it. Motion usually is. The harder part was that the strength was difficult to freeze. This publication documents the research that grew out of that problem: how a flag actually behaves, how that behavior can be studied, and what happens to a visual identity when motion stops being a layer applied to a fixed mark and becomes the identity itself." },
  { type: "p", text: "The research partly took the form of a custom browser-based tool, Flag Studio, that simulates flag behavior in real time. The tool is both an instrument of the research and one of its outcomes. The publication itself exists in two versions, and the difference between them is part of the point. This web version sets the text on animated cloth: the words sit on a moving surface and are read while that surface shifts. The PDF version holds the same words as a plain document, with none of the motion — the flattened record of a publication meant to move. The web version also links directly to Flag Studio, so the tool can be opened and used alongside the text." },
  { type: "p", text: "This research is focusing on two groups. The first is designers working with motion and identity systems, for whom the question of motion as a foundational rather than decorative element is live and contested. The second is the WdKA community and communication team, for whom the flag identity and Flag Studio are practical, usable outcomes." },
  { type: "spacer" },

  // Research Question
  { type: "p", indent: true, anchor: "research-question", text: "The idea came from a fascination with flags as a communication device that has worked for centuries, across languages and contexts, without needing translation. Part of what makes a flag compelling is that it is never the same twice. It is shaped by wind, light, and angle, and it never stops moving. A flag at rest is barely a flag at all." },
  { type: "p", text: "That fascination became a research question once a specific problem kept surfacing in the work. The moving version of the identity was always stronger than any still frame taken from it. The design itself was motion, and treating it as something layered onto a static mark had the relationship backwards." },
  { type: "p", text: "What happens to a visual identity when motion stops being a layer applied to a fixed mark and becomes the identity itself?" },
  { type: "p", text: "Most identities are made as a fixed thing first, a logo or a lockup, and motion is added afterward for digital use. The still version stays the authoritative one. This project tested the opposite. If a flag identity is designed through motion and simulation from the start, the question becomes what the identity now is. Is it the loop? Is it the tool that generates the loops? Can a moving identity even have a single authoritative frozen form, the way a logo does, or does freezing it always lose something essential?" },
  { type: "p", text: "Three sub-questions sit under it." },
  { type: "p", text: "What do flags traditionally communicate, and how do their physical properties (ratio, color, material, context) carry meaning?" },
  { type: "p", text: "How have contemporary designers and studios treated motion as a foundational part of identity rather than a finishing layer?" },
  { type: "p", text: "How can a custom simulation tool be used to study flag behavior, and what does building that tool reveal about designing an identity through motion?" },
  { type: "p", text: "The first sub-question establishes what a flag is and what it claims. The second positions the project within current practice, where the relationship between motion and identity is actively contested. The third concerns the method itself: Flag Studio was built to answer the research question, and building it became part of the answer." },
  { type: "spacer" },

  // Research Approach
  { type: "p", indent: true, anchor: "research-approach", text: "This research combines three modes of working, following the Circle of Doing Research." },
  { type: "p", text: "Research by making. The core of the project: design experiments, physical prototypes, fabric and pin tests, and the building of Flag Studio, a browser-based cloth simulation tool. Making was where the conclusions came from, not where they were illustrated. Several of the most important findings, including the central research question, only became visible through building, failing, and rebuilding." },
  { type: "p", text: "Research of context. Historical and contemporary sources on flags as communication systems and as an artistic medium, and on motion as part of identity design: vexillology (Whitney Smith, Ted Kaye), media theory (Marshall McLuhan), the theory of the apparatus (Vilém Flusser), and contemporary identity practice (Studio Dumbar, DIA, the 019 flagpole program, Random Studio). Research Through Design (Zimmerman, Forlizzi, and Evenson) provides the framework for treating Flag Studio itself as a research contribution." },
  { type: "p", text: "Participatory research. Conversations with people in the field. Supervision with Gabrielle Marks and Deanna Herst throughout. A conversation with Erik de Vlaam at Studio Dumbar, whose critique directly redirected the work. The WdKA communication team, a real user of the tool. Denzel Balois, who contributed the sound design. Kimmy Spreeuwenberg, WdKA Graphic Design tutor, who advised pushing the project past merchandise and deliverables toward something more artistic. Daan Dominic at Builders Club, consulted on extending the 3D simulation." },
  { type: "p", text: "The three modes were not sequential. Reading shaped what got built, building exposed what needed reading, and conversations cut across both. This publication follows that process rather than presenting a clean line from question to answer. Where the work took a wrong turn, the wrong turn is kept in." },
  { type: "spacer" },

  // 1
  { type: "p", indent: true, anchor: "section-1", text: "1. Every flag makes a claim. A national flag claims territory. A racing flag claims a state of play: in Formula 1, each color communicates a specific condition, yellow for hazard, red for a full stop, checkered for completion. A maritime flag claims identity or intent. The historic chart of maritime signal flags shows hundreds of them functioning as a single communication protocol at sea, each one carrying precise meaning through color, pattern, and proportion (Smith)." },
  { type: "image", src: "imgs/1 Charles Copley, Chart of Maritime Flags of the World.png", caption: "Charles Copley, Chart of Maritime Flags of the World, 1851 — flags as a shared communication protocol at sea. Public domain, via Wikimedia Commons." },
  { type: "p", text: "What makes flags remarkable as a communication device is that this system has worked for centuries, across languages, without translation. A flag is recognized rather than read." },
  { type: "p", text: "Ratio is part of that meaning, and it is never accidental. Switzerland's flag is square, Germany's is 3:5. Qatar's is 11:28, an extreme horizontal strip. (There is also Nepal, but that's for another time.) These ratios are design decisions. They affect how a flag reads in wind, at distance, and in context. A wider flag catches wind differently, drapes differently, and carries a different kind of energy. The Flags of the World comparative chart makes this visible: lined up side by side, the same object becomes a different object depending on its proportions (Flags of the World)." },
  { type: "p", text: "For the graduation identity, a 4:7 ratio was chosen as the default. It gives the flag a horizontal sweep that reads more as a banner than a standard, less formal and better suited to movement. But the graduation show needs materials in many formats, including screens, posters, banners, and signage, each with its own aspect ratio. So 4:7 is the primary flag, but not the only one. Each format became its own flag simulation, and each ratio changes how the identity moves and feels. The identity is a family of flags." },
  { type: "image", src: "imgs/2 One of the early sketches with 4 7 ratio .png", caption: "One of the early sketches with 4:7 ratio." },
  { type: "p", text: "Not every flag is designed with this kind of intention. The advertising flag, the teardrop or feather banner outside car dealerships and beach bars, is a flag stripped of meaning. It claims nothing except attention. The graduation flag had to avoid that. It should carry weight without being heavy." },
  { type: "p", text: "Then there is nationalism. Flags are so strongly tied to national identity that any new flag risks inheriting that association. The design avoids this deliberately. There is no coat of arms, no centered emblem, no symmetrical color blocking. The fabric is transparent, and you can see through it. A national flag is opaque by nature. It blocks out the world behind it to assert its own claim. A transparent flag does the opposite. It layers itself over reality instead of replacing it. This is a material choice and a conceptual one at the same time." },
  { type: "p", text: "The color is a single green, dark green on light green. It references Rotterdam directly, not a nation. Using one color avoids the multicolor palette of most graduation shows and keeps the identity focused." },
  { type: "spacer" },

  // 2
  { type: "p", indent: true, anchor: "section-2", text: "2. Whitney Smith, who coined the word “vexillology” in 1957, spent his career arguing that flags deserve serious study, as designed systems where color, proportion, symbolism, and construction all carry meaning." },
  { type: "p", text: "Ted Kaye's Good Flag, Bad Flag distills flag design into five principles, among them simplicity, meaningful symbolism, limited color, and no lettering (Kaye). The graduation flag deliberately breaks several. It uses typography, it is monochromatic, and the lettering is the design. This tension is intentional. The flag functions as a graphic identity, not as traditional vexillography. But knowing the rules matters: you have to understand what a flag normally does to see what this one chooses not to do." },
  { type: "p", text: "Vexillography itself offers a useful distinction. A logo is a still image made for pages, screens, and billboards. A flag is alternately draped and fluttering, seen from many distances and angles, including the reverse. That difference is exactly the gap this project ran into. The design that works as a still image is not the design that works on fabric in wind. A flag is closer to a moving identity than to a logo, even before any motion is deliberately added to it. Marshall McLuhan's claim that the medium is the message applies almost too neatly here — a flag's meaning is inseparable from the fact that it moves, drapes, and is seen in wind (McLuhan)." },
  { type: "p", text: "Designers do not agree on what motion is for. For most of its history, identity design has produced a fixed mark first and added motion afterward, as a finishing layer for digital use. A growing number of studios argue the opposite. DIA, the New York and Geneva studio, builds what it calls kinetic identity, where motion is present from the start and the typographic system is designed to move. Mitch Paone of DIA has described the studio's frustration with animated type as a simple on-and-off transition, and their pursuit instead of identities built so that motion is the way the work is generated, not a layer added afterward (Paone). Studio Dumbar takes a similar position, treating motion as a fundament of expression alongside typography, color, and composition." },
  { type: "p", text: "This project takes that argument and pushes it onto an object that has always moved. If a flag is already a moving thing, and motion is already understood as foundational to identity, then the flag is an obvious place to test the idea." },
  { type: "p", text: "Studio Dumbar is relevant a second time. Their 3D flag work for the Utah Jazz used digital cloth simulation to show how an identity behaves in motion rather than as a flat graphic, and their Feyenoord identity extended fabric simulation to the club's jerseys. In both cases the behavior of the fabric is part of the identity. Random Studio's wind installation for C.P. Company at Galeries Lafayette pushes this further, using fabric set in motion by electric fans as the entire visual statement, with no graphics and no text. Together these show that wind-animated fabric can carry a design concept on its own." },
  { type: "image", src: "imgs/4 dumbar flag.png", caption: "Studio Dumbar, Utah Jazz identity — cloth simulation used to show identity behavior in motion. Screenshot from studiodumbar.com. © Studio Dumbar / Utah Jazz." },
  { type: "p", text: "The most significant contemporary reference for this project is the 019 flagpole program in Ghent. Since 2016 a 20-meter flagpole has functioned as a mobile exhibition space, with an archive of large-scale flags by artists and designers including Nora Turato, Tauba Auerbach, Na Kim, and Rem Koolhaas/OMA. A second pole repurposes a disused 1902 bronze statue. The program has run for over ten years. It proves that a flagpole is an exhibition format, and that a flag is a serious medium for visual communication in public space." },
  { type: "image", src: "imgs/3 019 Ghent.png", caption: "The 019 flagpole program, Ghent: a flagpole treated as a curated exhibition space. Source: 019-ghent.org." },
  { type: "p", text: "Rem Koolhaas's European flag proposal, exhibited at 019 in early 2016, replaced the EU's circle of stars with a barcode of member state flag colors. It asked whether a collective identity can be designed at all, or whether a flag can only honestly represent a group by showing its parts. This resonates directly with the graduation context. The flag represents hundreds of individual graduates, not a single unified position." },
  { type: "p", text: "The graduation flag shares the ambition of these references and differs in scale and permanence. The 019 flags are monumental and rotate every few months. The graduation flag is portable and temporary. But the principle is the same. The flag is a designed object that carries meaning, and increasingly that meaning lives in how it moves." },
  { type: "spacer" },

  // 3
  { type: "p", indent: true, anchor: "section-3", text: "3. I don't find joy in producing assets. Animating frames, rendering, exporting, repeating, this kind of work flattens an idea instead of opening it. I am drawn to building systems that explore a space rather than executing one fixed output by hand. So when the identity needed testing across many flag ratios and motion settings, building a tool was the natural move. The first intention was a small browser application to see how different ratios behave in wind. Partway through building it, the tool stopped being a way to generate flags and became a way to study them." },
  { type: "p", text: "Before building, I watched flags. Around the port, along the Maas, at events and construction sites. How they move in wind, how size changes the rhythm, how fabric weight changes the drape. The design has to work in the range between, and that range was the target for what the tool needed to simulate." },
  { type: "p", text: "I worked through three approaches and only understood the method in hindsight. First, the web tool: a browser application built on WebGL cloth physics, with real-time control of ratio, wind, turbulence, gravity, typography, color, and texture. Change the ratio and the motion changes in front of you. Increase the wind and you see the exact point where it becomes boring. The value is not speed for its own sake but that the variables stay live. You ask a question and see the answer immediately." },
  { type: "p", text: "Second, Cinema 4D. This was a detour. I assumed a more physically accurate simulation would give better answers, so I moved the work there. It did not. The cloth simulation and the graphic animation had to be built separately and rendered for each iteration, which is the destructive, produce-and-repeat work the tool was built to escape. I corrected it by returning to the browser and later moving to Houdini for final output." },
  { type: "p", text: "Third, Houdini, which is procedural and so suited final, high-quality simulation. Changes stay non-destructive, so I could test ratios and adjust the setup at any point without rebuilding it. It also produces perfect infinite loops, which the motion identity needs to tile seamlessly across screens and projections. The tool-switching was the method, but it was not planned. It happened because I kept being wrong about what I needed." },
  { type: "p", text: "A more specific wrong turn sat inside the web tool. For a long time the simulation pinned the flag along its entire vertical edge. Real flags are almost never attached this way; they are held at points, usually corners. With the whole edge fixed, the cloth could not move like real fabric, and I was missing a large amount of realism without noticing. Changing the pinning to two corners changed the motion completely. A small technical detail, but it taught me something: a simulation's defaults are not neutral. They quietly decide what kind of flag you can design." },
  { type: "image", src: "imgs/6 flag studio full edge .png", caption: "Whole edge attached — early Flag Studio, before pinning was reduced to corner points." },
  { type: "p", text: "Through building it, the web tool became something with a name, Flag Studio. It lets you enter text in both project typefaces, animate it, choose or build a custom ratio with a live preview, and pin the flag in different ways. For export I adapted functionality from open web projects and built an MP4 recorder that captures the WebGL canvas frame by frame. The wind is built as a progression: slow and gentle at first, speeding up in stages toward the event. This mirrors the sound design Denzel Balois created for the graduation campaign, a four-step progression from chill, slow sounds in the early Save the Date posts toward faster, more energetic sound for the show itself. Slow start, strong finish. Motion and sound follow the same curve. The intensity of the identity is designed over time, not fixed." },
  { type: "image", src: "imgs/5 flag studio final.png", caption: "Flag Studio, final version." },
  { type: "p", text: "Flusser's idea of the apparatus describes what the tool is. In Towards a Philosophy of Photography, he argues that a camera is not neutral; its built-in program defines the space of possible photographs, and the photographer works inside that space (Flusser). The web tool is the same. Its ratios, wind presets, and pinning modes define the space of possible flags. The pinning mistake was a direct example: the tool produced a narrower range of flags than I thought, because I had set its program too narrowly. Building the tool meant deciding what flags could exist within it, and that is a research act, not a technical one." },
  { type: "p", text: "This is why the tool counts as research. Research Through Design treats the designed artifact as a way of producing knowledge, judged by the rigor of the process, the invention involved, and whether the result is relevant and extensible (Zimmerman, Forlizzi, and Evenson). The web tool meets this: it produced findings I could not have reached by sketching, and the WdKA communication team can use and extend it." },
  { type: "p", text: "Testing produced concrete findings. Different ratios suit different content: large near-square flags worked best for two or three lines of text, while a 5:7 ratio worked better for longer strings. The 4:7 default sits between, wide enough for the typography to breathe and still recognizable as a real flag. Testing also corrected an early assumption. I had expected 4:7 to produce energetic motion. It does not. At 4:7 the flag moves in a slow undulation rather than a sharp flutter. That is a quality, not a fault, but it is not what I first claimed." },
  { type: "p", text: "The identity uses two typefaces. OT Jubilee Platinum Extralight Italic by OFF Type Foundry is the display face, a delicate calligraphic serif with visible history in its forms. ABC Diatype Bold by Dinamo is the secondary face, geometric and contemporary. The contrast mirrors a tension in the project and in the academy itself. WdKA may not carry that name much longer; the institution is changing. The typography references something established while also being in motion and adapting, which fit a graduation moment that is both an ending and a beginning." },
  { type: "p", text: "The animated typography moves within the flag at varying speeds, creating a double motion: the fabric moves in the wind and the graphic moves independently across its surface. This is impossible on a traditional printed flag; it works only on screen or projected. It is the central visual idea of the identity, and the clearest case of motion behaving as the identity itself rather than as decoration." },
  { type: "spacer" },

  // 4
  { type: "p", indent: true, anchor: "section-4", text: "4. The clearest finding of the project is about cost and asymmetry. Motion reads almost for free. A still frame has to be earned. Throughout the work, a flag in motion looked right quickly, while pulling a single frame that carried the same design took real extra time and deliberate effort. I did manage it. The posters and still images work. But they did not fall out of the motion on their own. Each one had to be found and adjusted until it held. When a flag identity is designed through motion from the start, motion is the primary form, and the still frame becomes a deliberate extraction from it rather than the master the design begins with. That is the reverse of how identity design normally works, where the fixed mark comes first and motion is added later." },
  { type: "p", text: "This came from making, not from theory. Building the web tool and watching hundreds of loops, then working to pull usable stills from them, made the asymmetry impossible to ignore. It is also why the publication is intended to be experienced on the web, where the flags can move, rather than only as a PDF where they cannot." },
  { type: "p", text: "Making the flag physical produced a different and harder finding. I built a five-meter collapsible flagpole from three steel tubes of descending diameter, pinned so it can be assembled, taken apart, and transported. Standing next to a five-meter structure with fabric on it is a different kind of knowledge than moving a slider. The first fabric I ordered came out too small and too fragile. A scale that looked reasonable on screen did not hold up in reality. The simulation had taught me a great deal about how a flag moves, but almost nothing about how it feels at full size. Physical making corrected the digital work rather than confirming it." },
  { type: "image", src: "imgs/7 pole.png", caption: "5m telescopic pole test." },
  { type: "p", text: "I have since ordered samples in different materials, still to be tested in real conditions. The print approach is decided. Thinner fabric is semi-transparent, so it is printed on one side and the transparency stays part of the design. The 250-gram sports Lycra is no longer transparent at that weight, so it is printed double-sided. The portable stand is the part that still needs work. In wind, a tall flag carries real force, and a base that is both stable and easy to transport needs proper engineering before the flag can stand in public." },
  { type: "p", text: "The project was also tested by people, not only by making. A conversation with Erik de Vlaam at Studio Dumbar was the sharpest of these. His view was that the work is a simple idea with clean execution, and not much more than that. He suggested pushing the expression further: splitting the typography across multiple flags so words are revealed in sequence, and testing the extremes of ratio and behavior rather than settling on one resolved view. I agree with part of this. I could have experimented more with the overall expression instead of refining a single configuration. But the simplicity was a deliberate choice and it felt right, so I kept it. A graduation identity has to read instantly, across many formats, to a large and mixed audience. Clear and simple is not the same as underdeveloped." },
  { type: "p", text: "The more useful lesson from that conversation was about timing. I should have put the work in front of people much earlier, instead of developing it largely on my own and bringing it to others once it was already resolved. Early feedback would not have changed the simplicity, but it would have pushed the experiments while there was still room to act on them." },
  { type: "p", text: "Kimmy Spreeuwenberg's advice to steer away from a focus on merchandise also shaped the project's edges. It would have been easy to let the identity drift into a catalogue of products. Keeping the work centered on the flag and the tool kept the research question in view." },
  { type: "p", text: "What I do not know reaches past the fabric and the stand. The research question asked what a visual identity becomes when motion is the identity itself. The partial answer is that motion can carry an identity on its own, and the web tool is one way to design and study it. The harder, unresolved question is what the authoritative form of a moving identity is. A logo has a master file. A moving identity has motion as its master form, and any still is extracted from it. So if the identity is fundamentally a behavior, what is the thing that is actually owned and handed over — the loop, the set of presets, or the tool itself? This is the most genuinely unfinished part of the research, and the most interesting." },
  { type: "image", src: "imgs/8 poster mock.png", caption: "Final poster mockup — a still pulled from the motion." },
  { type: "spacer" },

  // Conclusion
  { type: "p", indent: true, anchor: "conclusion", text: "This project began with a task, designing the identity for a Graduation Show, and a fascination: the flag as a communication device that has worked for centuries and never stops moving. The research question only came into focus once the work was underway: what happens to a visual identity when motion stops being a layer applied to a fixed mark and becomes the identity itself?" },
  { type: "p", text: "The project answered it with a reversal. In ordinary identity design the fixed mark comes first and motion is added afterward. Here motion became the primary form and the still frame became something extracted from it, earned with effort rather than given. That answer was reached by making, not theory, and specifically by building a tool. Deciding what ratios, what wind, what kinds of pinning the tool would allow were decisions about what flags could exist at all, which is why building it counts as research and not only as production." },
  { type: "p", text: "The process was not clean, and the publication has tried to keep it that way: the Cinema 4D detour, the pinning mistake, the wrong claim about 4:7, the first fabric at the wrong scale. These corrections were the findings." },
  { type: "p", text: "What stays open is real. If an identity is fundamentally a behavior and not a mark, it isn't clear what the deliverable actually is, the thing owned, handed over, reused. I'm leaving that open on purpose. It's the most interesting part of the work and I don't want to force it shut." },
  { type: "spacer" },

  // Recommendations
  { type: "p", indent: true, anchor: "recommendations", text: "Several directions open out of this project, each a question it raised but couldn't pursue in time." },
  { type: "p", text: "The first is the expression of the identity. Erik de Vlaam's critique was that the work is one resolved configuration rather than an exploration of a range — splitting the typography across multiple flags so words reveal in sequence, testing the extremes of ratio and behavior. The web tool is well suited to this, and it is a next experiment I would show to others early rather than develop alone." },
  { type: "p", text: "The tool could also become a public instrument. Right now it is mainly my research tool, with the WdKA communication team as a first user. Developed further, with reliable print-ready export and real wind data, it could let a designer preview how a flag behaves in the actual place it will stand, closing part of the gap between simulation and physical reality." },
  { type: "p", text: "The relationship between ratio and motion deserves structured study. Wider flags move in slower undulations and different ratios suit different amounts of text, but these are observations from testing and intuition, not systematic comparison." },
  { type: "p", text: "The physical flag is the most unfinished part. The portable stand needs proper engineering before the flag can stand safely in wind. And the screen-based double motion — fabric moving while the graphic moves independently — has barely been tested as a physical or projected installation. That translation is its own design problem." },
  { type: "p", text: "The exhibition itself is still open. The most promising direction puts both sides of the project in one space: the web tool running live for visitors to manipulate, and the physical flag driven by an industrial fan. A viewer would see the same identity in both states at once. How to stage that so the two reinforce each other rather than compete is not yet resolved." },
  { type: "p", text: "Underneath all of these is the open question the conclusion ends on: what the deliverable of a behavior-based identity actually is. This project is one case study in that shift, not a general answer. As motion becomes a default rather than an addition in identity design, that question only gets more common, and it is the one I most want to keep working on." },
  { type: "spacer" },

  // Statement of Originality
  { type: "p", indent: true, anchor: "originality", text: "This document was written by me and in my own words, except for quotations from published and unpublished sources which are clearly indicated and acknowledged as such. I am conscious that the incorporation of material from other works or a paraphrase of such material without acknowledgement will be treated as plagiarism, subject to the custom and usage of the subject, according to the Hogeschool Rotterdam / WdKA regulations. The source of any media (picture, map, or illustration, AI bot such as Chat GPT) is also indicated, as is the source, published or unpublished, of any material not resulting from my own experimentation or observation." },
  { type: "p", text: "AI assistance (Claude, Anthropic) was used for editing, structuring, and language refinement of this text. All research, arguments, project work, and decisions are my own." },
  { type: "p", text: "1048261 — Albert Kozikowski — Rotterdam, 25 May 2026." },
  { type: "spacer" },

  // Sources
  { type: "p", anchor: "sources", text: "Copley, Charles. Chart of Maritime Flags of the World. 1851. Wikimedia Commons, commons.wikimedia.org/wiki/File:1851_chart_of_maritime_flags_of_the_world_by_Charles_Copley.jpg. Public domain." },
  { type: "p", text: "Flags of the World. FOTW Flags of the World website, fotw.info. Accessed 24 May 2026. The comparative proportion charts made it concrete that the same flag reads differently at different ratios, which led to choosing a 4:7 default over a more standard proportion." },
  { type: "p", text: "Flusser, Vilém. Towards a Philosophy of Photography. Translated by Anthony Mathews, Reaktion Books, 2000. Flusser argues that a tool's built-in program defines what can be produced with it. This framed the web tool: its ratios, wind presets, and pinning modes decide which flags can exist — and the pinning mistake showed a default quietly narrowing that space, which is why building the tool counts as a research act." },
  { type: "p", text: "Kaye, Ted, compiler. “Good” Flag, “Bad” Flag: How to Design a Great Flag. North American Vexillological Association, 2006. Kaye's five principles are the rule set the graduation flag deliberately breaks — typography, monochrome, lettering as the design. Used as a counter-reference: knowing the convention makes the departures read as choices." },
  { type: "p", text: "McLuhan, Marshall. Understanding Media: The Extensions of Man. McGraw-Hill, 1964. McLuhan's claim that the medium is the message supports the project's core argument that a flag's meaning is inseparable from how it moves, drapes, and is seen in wind — motion is not added to the identity, it is the identity." },
  { type: "p", text: "Paone, Mitch. “DIA Studio.” Interview by Demian Conrad and Rob van Leijsen. Graphic Design in the Post-Digital Age, Post-Digital Graphic Design research project, directed by Demian Conrad, HEAD – Genève (HES-SO), 2021, postdigitalgraphicdesign.com/interview/4/pdgd-itw-mitchpaone/. Accessed 24 May 2026. Paone describes motion as the means an identity is generated and the tool itself as the deliverable handed to clients. This shaped the research question and the framing of the web tool as a research outcome — and is the source the project's open question argues against." },
  { type: "p", text: "Random Studio. “A Wind Installation for C.P. Company at Galeries Lafayette.” Random Studio, random.studio/projects/a-wind-installation-for-c-p-company-at-galeries-lafayette. Accessed 24 May 2026. Fans set fabric in motion as the entire visual statement, with no graphics. Supports the claim that motion can carry an identity on its own, and informs the idea of a fan-driven physical flag for the exhibition." },
  { type: "p", text: "“S&D#025.” 019, 019-ghent.org/flags/flagpole/sd025/. Accessed 24 May 2026." },
  { type: "p", text: "“S&D#031.” 019, 019-ghent.org/flags/flagpole/sd031/. Accessed 24 May 2026. The 019 flagpole program treats a flagpole as a curated exhibition format and is the project's closest contemporary precedent. It also works by contrast: 019's permanent, monumental poles sharpened this project's emphasis on a portable, temporary construction." },
  { type: "p", text: "Smith, Whitney. Flags Through the Ages and Across the World. McGraw-Hill, 1975. Smith established flags as designed systems in which proportion and material carry meaning. This grounded treating the 4:7 ratio and transparent fabric as identity decisions, not decoration." },
  { type: "p", text: "Studio Dumbar/DEPT®. “Feyenoord.” Studio Dumbar, studiodumbar.com/work/feyenoord. Accessed 24 May 2026." },
  { type: "p", text: "Studio Dumbar/DEPT®. “Utah Jazz.” Studio Dumbar, studiodumbar.com/work/utah-jazz-50. Accessed 24 May 2026. Studio Dumbar's identities treat motion and material behavior as built-in systems. They informed the decision to treat cloth simulation as a legitimate identity design method rather than a rendering trick." },
  { type: "p", text: "Zimmerman, John, Jodi Forlizzi, and Shelley Evenson. “Research Through Design as a Method for Interaction Design Research in HCI.” Proceedings of the SIGCHI Conference on Human Factors in Computing Systems, CHI '07, Association for Computing Machinery, 2007, pp. 493–502. Provides the framework for treating the web tool as a research contribution. Its four criteria — process, invention, relevance, extensibility — were used to argue the tool produces knowledge unreachable by sketching." },
  { type: "p", text: "“Editing and language assistance.” Claude Opus 4.7, Anthropic, 2026, claude.ai. Generative AI tool used to edit, structure, and refine the text of this publication." },
];
